# This action enables building container images for farmer and node, can be triggered manually or by release creation.
#
# Container images are only pushed to GitHub Container Registry.
name: Docker build

on:
  workflow_dispatch:
  push:
    # docker/build-push-action demands a tag
    tags: '*'

# Incremental compilation here isn't helpful
env:
  CARGO_INCREMENTAL: 0

jobs:
  container-linux:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        image:
          - farmer
          - node
        platform:
          - arch: linux/amd64
            profile: production
            suffix: ubuntu-x86_64-${{ github.ref_name }}
            image-suffix: ''

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/subspace-${{ matrix.image }}
          tags: |
            type=ref,event=tag
          flavor: |
            latest=false
            suffix=${{ matrix.platform.image-suffix }}
      - name: Build and push ${{ matrix.image }} image
        id: build
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile-${{ matrix.image }}
          platforms: ${{ matrix.platform.arch }}
          # Only push for releases
          push: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            SUBSTRATE_CLI_GIT_COMMIT_HASH=${{ github.sha }}
            PROFILE=${{ matrix.platform.profile }}
            RUSTFLAGS=-C strip=debuginfo
